// ─── MOVIE VAULT DATA ────────────────────────────────────────────────────────
const MOVIES = [
  { t: "Monkey Man", k: ["action"] },
  { t: "The Raid", k: ["action"] },
  { t: "The Raid 2", k: ["action"] },
  { t: "Hard Boiled", k: ["action"] },
  { t: "The Night Comes for Us", k: ["action"] },
  { t: "Rebel Ridge", k: ["action"] },
  { t: "A Better Tomorrow", k: ["action"] },
  { t: "RRR", k: ["action"] },
  { t: "Kung Fu Hustle", k: ["action", "comedy"] },
  { t: "Crouching Tiger, Hidden Dragon", k: ["action"] },
  { t: "RoboCop", k: ["action", "sci-fi"] },
  { t: "Prey", k: ["action", "thriller"] },
  { t: "Die Hard", k: ["action"] },
  { t: "The Man from Nowhere", k: ["action", "thriller"] },
  { t: "Old Boy", k: ["thriller", "drama"] },
  { t: "Baby Driver", k: ["action", "thriller"] },
  { t: "Bullet Train", k: ["action", "comedy"] },
  { t: "Any John Wick Movie", k: ["action"] },
  { t: "The Beekeeper", k: ["action"] },
  { t: "Trap", k: ["thriller"] },
  { t: "Morbius", k: ["so-bad"] },
  { t: "Madame Web", k: ["so-bad"] },
  { t: "Twilight", k: ["so-bad", "drama"] },
  { t: "Willy's Wonderland", k: ["so-bad", "horror"] },
  { t: "How High", k: ["comedy"] },
  { t: "Pixels", k: ["so-bad", "comedy"] },
  { t: "Minecraft Movie", k: ["family"] },
  { t: "Hoodwinked", k: ["family"] },
  { t: "Astro Boy", k: ["family"] },
  { t: "Curious George", k: ["family"] },
  { t: "Any Barbie Movie", k: ["family"] },
  { t: "Sky High", k: ["family"] },
  { t: "Narnia", k: ["family", "franchise"] },
  { t: "Good Burger", k: ["family", "comedy"] },
  { t: "Chitty Chitty Bang Bang", k: ["family"] },
  { t: "E.T.", k: ["sci-fi", "family"] },
  { t: "Wallace and Gromit", k: ["family", "comedy"] },
  { t: "Jumanji", k: ["family"] },
  { t: "Night at the Museum", k: ["family", "comedy"] },
  { t: "Enchanted", k: ["family"] },
  { t: "The Lorax", k: ["family"] },
  { t: "Alice in Wonderland", k: ["family"] },
  { t: "Any Naked Gun Movie", k: ["comedy"] },
  { t: "Top Secret!", k: ["comedy"] },
  { t: "Airplane!", k: ["comedy"] },
  { t: "Kung Pow: Enter the Fist", k: ["comedy"] },
  { t: "This Is Spinal Tap", k: ["comedy"] },
  { t: "What We Do in the Shadows", k: ["comedy", "horror"] },
  { t: "Studio Ghibli (pick one)", k: ["anime", "family"] },
  { t: "A Silent Voice", k: ["anime", "drama"] },
  { t: "The Castle of Cagliostro", k: ["anime"] },
  { t: "Your Name", k: ["anime", "drama"] },
  { t: "The Garden of Words", k: ["anime", "drama"] },
  { t: "Suzume", k: ["anime"] },
  { t: "Weathering with You", k: ["anime"] },
  { t: "Sword of the Stranger", k: ["anime", "action"] },
  { t: "The Iron Claw", k: ["drama"] },
  { t: "Grave of the Fireflies", k: ["anime", "drama"] },
  { t: "Everything Everywhere All at Once", k: ["sci-fi", "drama", "comedy"] },
  { t: "Titanic", k: ["drama"] },
  { t: "Shin Godzilla", k: ["sci-fi"] },
  { t: "Godzilla Minus One", k: ["sci-fi", "drama"] },
  { t: "The Shawshank Redemption", k: ["drama"] },
  { t: "The Wolf of Wall Street", k: ["drama", "comedy"] },
  { t: "The Northman", k: ["drama", "action"] },
  { t: "Unbreakable", k: ["thriller"] },
  { t: "Interstellar", k: ["sci-fi", "drama"] },
  { t: "The Holdovers", k: ["drama", "comedy"] },
  { t: "The Resident Evil Movies", k: ["action", "horror", "franchise"] },
  { t: "DOOM", k: ["action", "so-bad"] },
  { t: "Halloween", k: ["horror"] },
  { t: "Weapons", k: ["horror", "thriller"] },
  { t: "Heretic", k: ["horror", "thriller"] },
  { t: "The Descent", k: ["horror"] },
  { t: "A Quiet Place", k: ["horror", "thriller"] },
  { t: "Sinners", k: ["horror", "thriller"] },
  { t: "The Thing", k: ["horror", "sci-fi"] },
  { t: "Cabin in the Woods", k: ["horror", "comedy"] },
  { t: "Keanu Reeves Night", k: ["actor-night", "action"] },
  { t: "Morgan Freeman Night", k: ["actor-night", "drama"] },
  { t: "Adam Sandler Night", k: ["actor-night", "comedy"] },
  { t: "Dwayne Johnson Night", k: ["actor-night", "action"] },
  { t: "Nicolas Cage Night", k: ["actor-night", "so-bad"] },
  { t: "Jason Statham Night", k: ["actor-night", "action"] },
  { t: "M. Night Shyamalan Night", k: ["actor-night", "thriller"] },
  { t: "Jim Carrey Night", k: ["actor-night", "comedy"] },
  { t: "Arnold Schwarzenegger Night", k: ["actor-night", "action"] },
  { t: "Ryan Reynolds Night", k: ["actor-night", "comedy"] },
  { t: "Samuel L. Jackson Night", k: ["actor-night", "action"] },
  { t: "Jackie Chan Night", k: ["actor-night", "action"] },
  { t: "Star Wars", k: ["franchise", "sci-fi"] },
  { t: "Fast & Furious", k: ["franchise", "action"] },
  { t: "Disney Animated", k: ["franchise", "family"] },
  { t: "Pixar", k: ["franchise", "family"] },
  { t: "Indiana Jones", k: ["franchise", "action"] },
  { t: "All Spider-Man Movies", k: ["franchise"] },
  { t: "All Batman Movies", k: ["franchise"] },
  { t: "The MCU", k: ["franchise", "action"] },
  { t: "The Snyderverse / DC", k: ["franchise"] },
  { t: "How to Train Your Dragon", k: ["franchise", "family"] },
  { t: "Godzilla", k: ["franchise", "sci-fi"] },
];

const FILTERS = [
  { id: "all", l: "All" },
  { id: "action", l: "Action" },
  { id: "anime", l: "Anime" },
  { id: "horror", l: "Horror" },
  { id: "comedy", l: "Comedy" },
  { id: "drama", l: "Drama" },
  { id: "sci-fi", l: "Sci-Fi" },
  { id: "family", l: "Family" },
  { id: "thriller", l: "Thriller" },
  { id: "so-bad", l: "So Bad It's Good" },
  { id: "franchise", l: "Franchise" },
  { id: "actor-night", l: "Actor Night" },
];
