const THEMES = [
  {
    n: "I Think They Just Killed That Guy",
    d: "Big fights, bigger explosions.",
    e: "💥",
    g: "linear-gradient(135deg,#b5111f,#e8453c)",
    tag: "action",
  },
  {
    n: "So Bad It's Good",
    d: "Terrible movies but somehow the most entertaining thing you've ever watched.",
    e: "🎬",
    g: "linear-gradient(135deg,#5e2a84,#af52de)",
    tag: "so-bad",
  },
  {
    n: "Childhood Throwback",
    d: "A movie that defined someone's childhood and probably nobody else's.",
    e: "👶",
    g: "linear-gradient(135deg,#b55a00,#f5b942)",
    tag: "family",
  },
  {
    n: "The Parody Hour",
    d: "Movies that exist almost entirely to make fun of other movies.",
    e: "🎭",
    g: "linear-gradient(135deg,#0a6a6a,#34c759)",
    tag: "comedy",
  },
  {
    n: "Anime Night",
    d: "Anime films, anime favourites, and everything in between.",
    e: "⛩️",
    g: "linear-gradient(135deg,#8a0038,#ff375f)",
    tag: "anime",
  },
  {
    n: "Bring Tissues",
    d: "The movies most likely to leave Nathan crying.",
    e: "😭",
    g: "linear-gradient(135deg,#102060,#0a84ff)",
    tag: "drama",
  },
  {
    n: "Horror",
    d: "Monsters, nightmares, jump scares, and poor life decisions.",
    e: "🎃",
    g: "linear-gradient(135deg,#5a0a0a,#e8453c)",
    tag: "horror",
  },
  {
    n: "One Actor Special",
    d: "An entire movie night dedicated to one actor's greatest hits.",
    e: "⭐",
    g: "linear-gradient(135deg,#065038,#34c759)",
    tag: "actor-night",
  },
  {
    n: "Franchise Deep Dive",
    d: "Marvel, Bay-Formers, Fast & Furious, all of the above.",
    e: "🏢",
    g: "linear-gradient(135deg,#5a4200,#f5b942)",
    tag: "franchise",
  },
  {
    n: "Brain Off, Action On",
    d: "No thinking required. Just sit back and enjoy the chaos.",
    e: "🧠",
    g: "linear-gradient(135deg,#6a3200,#e8453c)",
    tag: "action",
  },
  {
    n: "Sci-Fi",
    d: "Spaceships and stuff.",
    e: "🛰️",
    g: "linear-gradient(135deg,#073850,#0a84ff)",
    tag: "sci-fi",
  },
  {
    n: "Thrillers After Dark",
    d: "Twists, tension, and movies that keep everyone guessing.",
    e: "🔪",
    g: "linear-gradient(135deg,#3a0ca3,#af52de)",
    tag: "thriller",
  },
];
